<h1><?php echo $this->translate('title_blog_admin_index'); ?></h1>
<?php
$createUrl = $this->url(
    'blog-admin',
    array('controller' => 'admin', 'action' => 'create'),
    true
);
?>
<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th><?php echo $this->translate('label_blog_article_title') ?></th>
        <th><?php echo $this->translate('label_blog_article_category') ?></th>
        <th><?php echo $this->translate('label_blog_article_user') ?></th>
        <th><?php echo $this->translate('label_blog_article_status') ?></th>
        <th><?php echo $this->translate('label_blog_article_date') ?></th>
        <th width="70" style="text-align: center">
            <a href="<?php echo $createUrl; ?>"
               title="<?php echo $this->translate('label_create'); ?>"
               class="btn btn-mini"><i class="icon-plus"></i>
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->articleList as $article): ?>
        <?php
        $showUrl   = $this->url(
            'blog-article', array('url' => $article->getUrl()), true
        );
        $updateUrl = $this->url(
            'blog-admin/id',
            array(
                'controller' => 'admin',
                'action'     => 'update',
                'id'         => $article->getId(),
            ),
            true
        );
        $deleteUrl = $this->url(
            'blog-admin/id',
            array(
                'controller' => 'admin',
                'action'     => 'delete',
                'id'         => $article->getId(),
            ),
            true
        );
        ?>
        <tr>
            <td>
                <a href="<?php echo $showUrl; ?>">
                    <?php echo $article->getTitle() ?>
                </a>
            </td>
            <td><?php echo $article->getCategory() ?></td>
            <td><?php echo $article->getUser() ?></td>
            <td><?php echo $this->translate($article->getStatus()) ?></td>
            <td><?php echo $this->date($article->getDate()) ?></td>
            <td style="text-align: center">
                <a href="<?php echo $updateUrl; ?>"
                   title="<?php echo $this->translate('label_update'); ?>"
                   class="btn btn-mini"><i class="icon-pencil"></i>
                </a>
                <a href="<?php echo $deleteUrl; ?>"
                   title="<?php echo $this->translate('label_delete'); ?>"
                   class="btn btn-mini"><i class="icon-trash"></i>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
