<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                         => __DIR__ . '/Module.php',
    'Application\View\Helper\Date'               => __DIR__ . '/src/Application/View/Helper/Date.php',
    'Application\Listener\ApplicationListener'   => __DIR__ . '/src/Application/Listener/ApplicationListener.php',
    'Application\Listener\CompatibilityListener' => __DIR__ . '/src/Application/Listener/CompatibilityListener.php',
    'Application\Controller\IndexController'     => __DIR__ . '/src/Application/Controller/IndexController.php',
);
