<h1><?php echo $this->translate('title_blog_admin_index'); ?></h1>
<table class="table table-bordered table-striped table-hover">
<thead>
<tr>
<th><?php echo $this->translate('label_blog_article_title')?></th>
<th><?php echo $this->translate('label_blog_article_category')?></th>
<th><?php echo $this->translate('label_blog_article_user')?></th>
<th><?php echo $this->translate('label_blog_article_status')?></th>
<th><?php echo $this->translate('label_blog_article_date')?></th>
<th width="70" style="text-align: center">
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'admin', 'action' => 'create')); ?>" title="<?php echo $this->translate('label_create'); ?>" class="btn btn-mini"><i class="icon-plus"></i></a>
</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->articleList as $article): ?>
<tr>
<td><a href="<?php echo $this->url(array('url' => $article->getUrl()), 'blog-article'); ?>"><?php echo $article->getTitle()?></a></td>
<td><?php echo $article->getCategory()->getName()?></td>
<td><?php echo $article->getUser()->getName()?></td>
<td><?php echo $this->translate($article->getStatus())?></td>
<td><?php echo $this->date($article->getDate())?></td>
<td style="text-align: center">
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'admin', 'action' => 'update', 'id' => $article->getId())); ?>" title="<?php echo $this->translate('label_update'); ?>" class="btn btn-mini"><i class="icon-pencil"></i></a>
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'admin', 'action' => 'delete', 'id' => $article->getId())); ?>" title="<?php echo $this->translate('label_delete'); ?>" class="btn btn-mini"><i class="icon-trash"></i></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<div class="box info center">
<?php echo $this->paginate(array('module' => 'blog', 'controller' => 'admin', 'action' => 'index'), $this->pageHandling); ?>
</div>
