<?php
$this->headTitle('Startseite');
$this->headMeta()->setName('description', 'Mein ZF2 Blog wird migriert');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1.0'
);
$this->headLink(array(
    'rel'  => 'shortcut icon', 
    'type' => 'image/vnd.microsoft.icon', 
    'href' => $this->basePath() . '/img/favicon.ico'
));
$this->headLink()->appendStylesheet(
    $this->basePath() . '/css/bootstrap.min.css', 'screen, print'
);
$this->headLink()->appendStylesheet(
    $this->basePath() . '/css/styles.css', 'screen, print'
);
$this->headScript()->appendFile(
    $this->basePath() . '/js/html5shiv.js', 'text/javascript', 
    array('conditional' => 'lt IE 9')
);
$this->inlineScript()->appendFile(
    $this->basePath() . '/js/jquery-1.9.1.min.js', 'text/javascript'
);
$this->inlineScript()->appendFile(
    $this->basePath() . '/js/bootstrap.min.js', 'text/javascript'
);
?>
<?php echo $this->doctype() ?>
<html lang="de">
<head>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headLink() . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<?php echo $this->headStyle() . "\n"; ?>
</head>
<body>
<?php echo $this->layout()->header; ?>
<div class="container">
<div class="row">
<div class="content span9">
<?php // echo $this->showMessages($this->messages); ?>
<?php echo $this->layout()->content; ?>
</div>
<div class="sidebar span3">
<?php echo $this->layout()->sidebar; ?>
</div>
</div>
</div>
<?php echo $this->layout()->footer; ?>
<?php echo $this->inlineScript() ?>
</body>
</html>
