<h1><?php echo $this->translate('title_website'); ?></h1>
<h3><?php echo $this->translate('heading_default_index_blog'); ?></h3>
<table class="table table-striped table-hover">
<?php foreach($this->articleList as $article):?>
<tr>
<td><a href="<?php echo $this->url(array('url' => $article->getUrl()), 'blog-article'); ?>"><?php echo $article->getTitle()?></a></td>
<td><?php echo $article->getCategory()->getName();?></td>
<td><?php echo $article->getUser()->getName();?></td>
<td><?php echo $this->date($article->getDate());?> <?php echo $this->time($article->getDate());?></td>
</tr>
<?php endforeach; ?>
</table>
<a href="<?php echo $this->url(array('module' => 'blog'), 'default', true);?>" class="btn"><?php echo $this->translate('link_blog');?></a>
