<h1><?php echo $this->translate('title_blog_category_index'); ?></h1>
<table class="table table-bordered table-striped table-hover">
<thead>
<tr>
<th><?php echo $this->translate('label_blog_category_name')?></th>
<th width="70" style="text-align: center">
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'category', 'action' => 'create')); ?>" title="<?php echo $this->translate('label_create'); ?>" class="btn btn-mini"><i class="icon-plus"></i></a>
</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->categoryList as $category): ?>
<tr>
<td><a href="<?php echo $this->url(array('url' => $category->getUrl()), 'blog-category'); ?>"><?php echo $category->getName()?></a></td>
<td style="text-align: center">
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'category', 'action' => 'update', 'id' => $category->getId())); ?>" title="<?php echo $this->translate('label_update'); ?>" class="btn btn-mini"><i class="icon-pencil"></i></a>
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'category', 'action' => 'delete', 'id' => $category->getId())); ?>" title="<?php echo $this->translate('label_delete'); ?>" class="btn btn-mini"><i class="icon-trash"></i></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
