<?php 
    $lang = \Locale::getPrimaryLanguage(\Locale::getDefault()); 
?>

<h1><?php echo $this->translate('title_website'); ?></h1>
<h3><?php echo $this->translate('heading_default_index_blog'); ?></h3>
<table class="table table-striped table-hover">
<?php foreach($this->articleList as $article):?>
<tr>
<td><a href="<?php echo $this->url('blog-article', array('url' => $article->getUrl(), 'lang' => $lang)); ?>"><?php echo $article->getTitle()?></a></td>
<td><?php echo $article->getCategory()->getName();?></td>
<td><?php echo $article->getUser()->getName();?></td>
<td><?php echo $this->date($article->getDate());?></td>
</tr>
<?php endforeach; ?>
</table>
<a href="<?php echo $this->url('blog', array('lang' => $lang));?>" class="btn"><?php echo $this->translate('link_blog');?></a>
